/**
 * i18n.js — t()/tr with embedded dicts (generated by build.mjs).
 * Key-fallback behavior identical to the current app: missing key -> key.
 */
import { LANGS } from './dicts.generated.js';

export const SUPPORTED_LANGS = Object.keys(LANGS);

let lang = 'en';
let dict = LANGS.en ?? {};

export function getLang() {
  return lang;
}

export function setLang(code) {
  lang = SUPPORTED_LANGS.includes(code) ? code : 'en';
  dict = LANGS[lang] ?? {};
  document.documentElement.lang = lang;
}

export function t(key) {
  return dict[key] || key;
}

export const tr = {
  get dict() {
    return dict;
  }
};
