// gen-tokens.mjs — extract theme token blocks from src/app.css into
// web/kernel/tokens.css (Phase 1 kernel; run once, output committed).
import fs from 'node:fs';

const src = fs.readFileSync('src/app.css', 'utf8');
const fontCss = fs.readFileSync('src/lib/fonts/noto-cjk.css', 'utf8');

const wanted = new Set([
  ':root', '.dark', '.nord', '.dracula', '.cobalt', '.solarized', '.gruvbox',
  '.amoled', '.snow', '.gruvbox-light', '.ionized-purple', '.ionized-red', '.ionized-cyan'
]);

const lines = src.split('\n');
const blocks = [];

for (let i = 0; i < lines.length; i++) {
  const line = lines[i].trim();
  if (!wanted.has(line.replace(/[{}].*$/, '').trim())) continue;
  // match top-level `selector {` (column 0, e.g. `.nord {`) and plain `:root {`
  const m = line.match(/^(:root|\.\w[\w-]*)\s*\{\s*$/);
  if (!m) continue;
  const selector = m[1];
  const body = [];
  let j = i + 1;
  while (j < lines.length && !/^\}\s*$/.test(lines[j].trim())) {
    body.push(lines[j]);
    j++;
  }
  if (j >= lines.length) continue;
  blocks.push({ selector, body: body.join('\n').trim() });
  i = j;
}

const out = [
  '/* tokens.css — generated by scripts/gen-tokens.mjs from src/app.css; do not edit */',
  '/* Theme color tokens + bundled CJK font faces (Noto Sans + SC/JP/KR). */'
];
for (const { selector, body } of blocks) {
  out.push(`\n${selector} {`);
  out.push(body);
  out.push('}');
}

out.push('\n' + fontCss.replace(/url\('\.\/([^']+)'\)/g, "url('/fonts/$1')"));

fs.writeFileSync('web/kernel/tokens.css', out.join('\n') + '\n');
console.log('tokens.css written —', blocks.map((b) => b.selector).join(', '));
