// build.mjs — Phase 1 build for the vanilla frontend (web/ -> dist-web/).
// esbuild (bundle+minify, lazy chunks) + tailwind CLI + asset copy + version stamp.
//
// Usage:
//   node web/build.mjs            # one-shot build
//   node web/build.mjs --watch    # watch mode (esbuild + tailwind)
import { build, context } from 'esbuild';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const WEB = path.join(ROOT, 'web');
const OUT = path.join(ROOT, 'dist-web');
const WATCH = process.argv.includes('--watch');

const APP_VERSION = process.env.APP_VERSION || '0.4.3';
const APP_BUILD = process.env.APP_BUILD || '0x07D21';

// ---- 1. generate embedded i18n dicts from lang/*.json (source of truth) ----
function genDicts() {
  const langsDir = path.join(ROOT, 'frontend/v2/lang');
  const entries = fs.readdirSync(langsDir).filter((f) => f.endsWith('.json'));
  const out = ['/* generated by build.mjs — do not edit */', 'export const LANGS = {'];
  for (const f of entries.sort()) {
    const code = f.replace('.json', '');
    const dict = JSON.parse(fs.readFileSync(path.join(langsDir, f), 'utf8'));
    out.push(`  '${code}': ${JSON.stringify(dict)},`);
  }
  out.push('};');
  fs.writeFileSync(path.join(WEB, 'kernel/dicts.generated.js'), out.join('\n') + '\n');
  console.log(`[build] dicts.generated.js (${entries.length} languages)`);
}

// ---- 2. esbuild ----
const esbuildOptions = {
  entryPoints: [path.join(WEB, 'index.js')],
  bundle: true,
  outdir: path.join(OUT, 'assets'),
  format: 'esm',
  splitting: true,
  minify: !WATCH,
  sourcemap: WATCH,
  target: ['es2022'],
  logLevel: 'info',
  loader: { '.woff2': 'file', '.ttf': 'file' },
};

// ---- 3. tailwind (v4 CLI) ----
function tailwind(watch) {
  const bin = path.join(ROOT, 'node_modules/.bin/tailwindcss');
  const args = [
    '-i', path.join(WEB, 'styles/input.css'),
    '-o', path.join(OUT, 'assets/app.css'),
    '--minify'
  ];
  if (watch) args.push('--watch');
  try {
    execSync(`"${bin}" ${args.join(' ')}`, { stdio: 'inherit' });
  } catch (e) {
    console.error('[build] tailwind failed:', e.message);
    process.exit(1);
  }
}

// ---- 3.5 copy katex dist (css + fonts) for lazy math rendering ----
function copyKatex() {
  const src = path.join(ROOT, 'node_modules/katex/dist');
  const dst = path.join(OUT, 'assets/katex');
  fs.cpSync(src, dst, { recursive: true });
}

// ---- 4. copy static assets (+ service worker at root scope) ----
function copyStatic() {
  const src = path.join(WEB, 'static');
  if (!fs.existsSync(src)) return;
  fs.cpSync(src, OUT, { recursive: true });
  const sw = path.join(WEB, 'sw.js');
  if (fs.existsSync(sw)) fs.copyFileSync(sw, path.join(OUT, 'sw.js'));
}

// ---- 5. index.html + version stamp ----
function writeHtml() {
  const html = fs
    .readFileSync(path.join(WEB, 'index.html'), 'utf8')
    .replaceAll('__APP_VERSION__', APP_VERSION)
    .replaceAll('__APP_BUILD__', APP_BUILD);
  fs.writeFileSync(path.join(OUT, 'index.html'), html);
  fs.writeFileSync(
    path.join(OUT, 'build.json'),
    JSON.stringify({ version: APP_BUILD }) + '\n'
  );
}

function banner() {
  console.log(`[build] llama-ui web ${APP_VERSION} (${APP_BUILD}) -> dist-web`);
}

genDicts();
banner();
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
tailwind(WATCH);
copyKatex();
copyStatic();
writeHtml();

if (WATCH) {
  const ctx = await context(esbuildOptions);
  await ctx.watch();
  console.log('[build] watching for changes…');
} else {
  await build(esbuildOptions);
  console.log('[build] done.');
}
